version: '3.0'

services:
  main:
    container_name: main
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
#      - /node_modules
    ports:
      - 5001:5001
#      //- 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a32323232
      - POSTGRES_DB=product-database
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: